set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/eymen/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/eymen/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/RV32_pipelined"
set ::env(DESIGN_NAME) "cpu"
set ::env(VERILOG_FILES) "/openlane/designs/RV32_pipelined/src/cpu.v /openlane/designs/RV32_pipelined/src/logical_unit.v /openlane/designs/RV32_pipelined/src/shift_right.v /openlane/designs/RV32_pipelined/src/ALU_LL.v /openlane/designs/RV32_pipelined/src/instr_dec.v /openlane/designs/RV32_pipelined/src/Datapath.v /openlane/designs/RV32_pipelined/src/shifter.v /openlane/designs/RV32_pipelined/src/control_unit.v /openlane/designs/RV32_pipelined/src/FunctionUnit.v /openlane/designs/RV32_pipelined/src/mux_2to1.v /openlane/designs/RV32_pipelined/src/instr_mem.v /openlane/designs/RV32_pipelined/src/pc_updater.v /openlane/designs/RV32_pipelined/src/immed_gen.v /openlane/designs/RV32_pipelined/src/pipeline_reg.v /openlane/designs/RV32_pipelined/src/Memblock.v /openlane/designs/RV32_pipelined/src/data_mem.v /openlane/designs/RV32_pipelined/src/regfile.v /openlane/designs/RV32_pipelined/src/full_adder_LL_nodelay.v /openlane/designs/RV32_pipelined/src/ripple_carry_adder_subtractor.v"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "20.0"
set ::env(DESIGN_IS_CORE) "1"
set ::env(FP_SIZING) "absolute"
set ::env(DIE_AREA) "0 0 1000 1000"
set ::env(ROUTING_CORES) "6"
set ::env(KLAYOUT_XOR_THREADS) "6"
set ::env(SYNTH_NO_FLAT) "1"
